Repository PennyLaneAI/qml, pull requests merged in 2019-10, with the labels that each got.

#5 added tutorial
  implementations.rst
  implementations/doubly_stochastic/single_shot.png
  implementations/tutorial_doubly_stochastic.py
Labels: review-ready

#6 Added basic CircleCI build and deploy
  .circleci/config.yml
  conf.py
  requirements.txt
Labels: enhancement, review-ready

#8 Update advanced usage tutorial with tensor observable feature
  beginner/tutorial_advanced_usage.py
Labels: merge-ready

#10 Added a featured gallery/carousel
  index.rst
  xanadu_theme/layout.html
  xanadu_theme/static/css/lightslider.min.css
  xanadu_theme/static/img/controls-old.png
  xanadu_theme/static/js/lightslider.min.js
  xanadu_theme/static/xanadu.css_t
Labels: review-ready

#13 Updating QGAN tutorial
  implementations.rst
  implementations/tutorial_QGAN.py
  requirements.txt
Labels: merge-ready
