Repository PennyLaneAI/qml, pull requests merged in 2020-02, with the labels that each got.

#31 Adds PennyLane-QChem tutorials
  .gitignore
  _static/thumbs/vqe_output_22_0.png
  _static/xanadu_gallery.css
  beginner.rst
  beginner/h2o.xyz
  beginner/quantum_chemistry/hf_references.png
  beginner/quantum_chemistry/sketch_active_space.png
  beginner/quantum_chemistry/sketch_circuit.png
  beginner/quantum_chemistry/sketch_pennylane-qchem.png
  beginner/quantum_chemistry/water_structure.png
  beginner/tutorial_quantum_chemistry.py
  implementations.rst
  implementations/h2.xyz
  implementations/tutorial_quantum_natural_gradient.py
  implementations/tutorial_vqe.py
  implementations/variational_quantum_eigensolver/pes_h2.png
  implementations/variational_quantum_eigensolver/sketch_circuit.png
  implementations/variational_quantum_eigensolver/vqe_output_22_0.png
  requirements.txt
  xanadu_theme/layout.html
Labels: merge-ready, on hold, qchem

#41 Port state preparation tutorial to use default.qubit
  implementations.rst
  implementations/tutorial_state_preparation.py
Labels: documentation, review-ready

#40 Ensemble parallel
  .circleci/config.yml
  implementations.rst
  implementations/ensemble_multi_qpu/diagram.png
  implementations/ensemble_multi_qpu/diagram.svg
  implementations/ensemble_multi_qpu/diagram_circuits.png
  implementations/ensemble_multi_qpu/diagram_circuits.svg
  implementations/ensemble_multi_qpu/params.npy
  implementations/tutorial_ensemble_multi_qpu.py
  requirements.txt
Labels: documentation, merge-ready

#37 Tutorials: VQE with parallel QPUs on Rigetti-Forest
  .pylintrc
  beginner/tutorial_quantum_chemistry.py
  implementations.rst
  implementations/tutorial_vqe.py
  implementations/tutorial_vqe_parallel.py
  implementations/vqe_parallel/RY_params.npy
  implementations/vqe_parallel/diagram.png
  implementations/vqe_parallel/diagram.svg
  implementations/vqe_parallel/h2_0.30.xyz
  implementations/vqe_parallel/h2_0.50.xyz
  implementations/vqe_parallel/h2_0.70.xyz
  implementations/vqe_parallel/h2_0.90.xyz
  implementations/vqe_parallel/h2_1.10.xyz
  implementations/vqe_parallel/h2_1.30.xyz
  implementations/vqe_parallel/h2_1.50.xyz
  implementations/vqe_parallel/h2_1.70.xyz
  implementations/vqe_parallel/h2_1.90.xyz
  implementations/vqe_parallel/h2_2.10.xyz
  implementations/vqe_parallel/vqe_parallel.zip
  xanadu_theme/layout.html
Labels: documentation, pending-release, qchem

#47 Fix PennyLane link bug
  xanadu_theme/layout.html
Labels: bug

#29 [REDESIGN] Allows demos to be filtered by frameworks
  _static/xanadu_gallery.css
  custom_directives.py
  demonstrations.rst
  xanadu_theme/filters.html
  xanadu_theme/layout.html
  xanadu_theme/static/xanadu.css_t
Labels: review-ready

#49 [REDESIGN] Update navbar links
  xanadu_theme/header.html
Labels: on hold

#50 [REDESIGN] Add glossary structure
  concepts.rst
  concepts/autograd_quantum.rst
  concepts/hybrid_computation.rst
  concepts/quantum_nodes.rst
  concepts/varcirc.rst
  glossary.rst
  glossary/automatic_differentiation.rst
  glossary/circuit_ansatz.rst
  glossary/hybrid_computation.rst
  glossary/quantum_embedding.rst
  glossary/quantum_gradient.rst
  glossary/variational_circuit.rst
  index.rst
Labels: review-ready

#51 Better fix for iteration issue
  .circleci/config.yml
  implementations/tutorial_embeddings_metric_learning.py
Labels: bug

#38 [REDESIGN] What is QML section
  .circleci/config.yml
  _static/brain_board.png
  _static/dummy.png
  _static/whatisqml/applications.png
  _static/whatisqml/drawings.svg
  _static/whatisqml/gpu_to_qpu.png
  _static/whatisqml/jigsaw.png
  _static/whatisqml/quantum_devices_ai.png
  _static/whatisqml/trainable_circuit.png
  demonstrations/tutorial_embeddings_metric_learning.py
  index.rst
  references.bib
  whatisqml.rst
Labels: documentation, review-ready

#55 [REDESIGN] Improve embeddings tutorial
  demonstrations/tutorial_embeddings_metric_learning.py
Labels: demos

#52 [REDESIGN] Add video page
  conf.py
  custom_directives.py
  index.rst
  videos.rst
  xanadu_theme/layout.html
  xanadu_theme/static/xanadu.css_t
Labels: review-ready
