Repository PennyLaneAI/qml, pull requests merged in 2020-11, with the labels that each got.

#110 Add Keras/TorchNN tutorial
  _static/Keras_logo.png
  _static/PyTorch_icon.png
  demonstrations/qnn_module/qnn2_keras.png
  demonstrations/qnn_module/qnn2_keras.svg
  demonstrations/qnn_module/qnn2_torch.png
  demonstrations/qnn_module/qnn2_torch.svg
  demonstrations/qnn_module/qnn_keras.png
  demonstrations/qnn_module/qnn_keras.svg
  demonstrations/qnn_module/qnn_torch.png
  demonstrations/qnn_module/qnn_torch.svg
  demonstrations/tutorial_qnn_module_tf.py
  demonstrations/tutorial_qnn_module_torch.py
  demos_basics.rst
  requirements.txt
Labels: review-ready

#157 Updates README with demo categorization instructions
  README.md
Labels: documentation, review-ready

#164 Replace VQECost with ExpvalCost
  .circleci/config.yml
  demonstrations/tutorial_qaoa_intro.py
  demonstrations/tutorial_vqe.py
  demonstrations/tutorial_vqe_parallel.py
  demonstrations/tutorial_vqe_qng.py
  demonstrations/tutorial_vqe_uccsd_obs.py
Labels: review-ready

#167 Add very minor style corrections in the References section of the tutorial "VQE in different spin sectors"
  demonstrations/tutorial_vqe_uccsd_obs.py
Labels: review-ready

#166 Update requirements to have pyscf==1.7.2 and no scipy pinning
  requirements.txt
Labels: do not merge

#170 [Community demo] Trainable Quantum Convolution
  demos_community.rst
  xanadu_theme/static/xanadu.css_t
Labels: demos, review-ready
