Repository PennyLaneAI/qml, pull requests merged in 2020-05, with the labels that each got.

#74 Improve images for variational circuits article
  _static/concepts/circuit_embedding.svg
  _static/concepts/concepts.png
  _static/concepts/grad.png
  _static/concepts/variational_circuit.png
  _static/concepts/variational_circuit2.png
  _static/concepts/variational_rough.png
  glossary/variational_circuit.rst
Labels: glossary

#75 Improve images for gradient article
  _static/concepts/gradients2.png
  _static/concepts/quantum_gradient.png
  _static/concepts/quantum_gradient.svg
  _static/concepts/quantumnode.png
  _static/concepts/quantumnode_detail.png
  _static/concepts/varcirc.png
  glossary/quantum_gradient.rst
Labels: glossary

#76 Update images in hybrid article
  _static/concepts/hybrid_graph.png
  _static/concepts/vqe.png
  glossary/hybrid_computation.rst
Labels: glossary

#78 Fix QGAN tutorial
  demonstrations/tutorial_QGAN.py
Labels: bug

#88 Add download link for data to Variational classifier tutorial
  demonstrations/tutorial_variational_classifier.py
Labels: bug

#87 Add download link for sine.txt data to function fitting tutorial
  demonstrations/quantum_neural_net.py
Labels: bug

#85 Demonstration on the Rosalin shot-frugal optimization
  demonstrations.rst
  demonstrations/rosalin/rosalin_thumb.png
  demonstrations/tutorial_rosalin.py
Labels: demos, merge-ready

#90 Upgrade QML website to use Sphinx-Gallery v0.6.2
  .circleci/comment.py
  .circleci/config.yml
  .gitignore
  conf.py
  requirements.txt
  xanadu_theme/layout.html
Labels: enhancement, review-ready

#93 Stochastic parameter-shift rule
  demonstrations.rst
  demonstrations/stochastic_parameter_shift/parameter_shift_rule.png
  demonstrations/stochastic_parameter_shift/quantum_circuit.png
  demonstrations/stochastic_parameter_shift/stochastic_parameter_shift.png
  demonstrations/stochastic_parameter_shift/stochastic_parameter_shift_thumbnail.png
  demonstrations/tutorial_stochastic_parameter_shift.py
Labels: demos, review-ready

#92 Fix Rigetti demonstrations
  .circleci/config.yml
  README.md
  demonstrations/ensemble_multi_qpu/diagram.svg
  demonstrations/ensemble_multi_qpu/ensemble_diagram.png
  demonstrations/tutorial_ensemble_multi_qpu.py
  demonstrations/tutorial_vqe_parallel.py
  demonstrations/vqe_parallel/diagram.svg
  demonstrations/vqe_parallel/vqe_diagram.png
  requirements.txt
  xanadu_theme/layout.html
Labels: bug
