Repository PennyLaneAI/qml, pull requests merged in 2020-10, with the labels that each got.

#121 Update tutorials using PL-QChem functions to build the electronic Hamiltonian
  demonstrations/quantum_chemistry/sketch_active_space.png
  demonstrations/tutorial_quantum_chemistry.py
  demonstrations/tutorial_vqe.py
  demonstrations/tutorial_vqe_parallel.py
  demonstrations/tutorial_vqe_qng.py
Labels: merge-ready, qchem

#116 Pasqal demo
  .circleci/config.yml
  demonstrations/pasqal/Eiffel_tower_data.dat
  demonstrations/pasqal/pasqal_thumbnail.png
  demonstrations/tutorial_pasqal.py
  demos_research.rst
  requirements.txt
Labels: merge-ready

#109 Add tutorial: VQE in different spin sectors
  demonstrations/tutorial_vqe_uccsd_obs.py
  demonstrations/vqe_uccsd_obs/energy_spectra_h2_sto3g.png
  demonstrations/vqe_uccsd_obs/thumbnail_spectra_h2.png
  demos_basics.rst
Labels: demos, qchem, review-ready

#135 Expand glossary
  glossary.rst
  xanadu_theme/static/xanadu.css_t
Labels: merge-ready
