Repository PennyLaneAI/qml, pull requests merged in 2021-07, with the labels that each got.

#270 Adds tutorial on Givens rotations
  demonstrations/givens_rotations/Givens_rotations.png
  demonstrations/givens_rotations/Givens_rotations_1.png
  demonstrations/givens_rotations/Givens_rotations_2.png
  demonstrations/givens_rotations/circuit.png
  demonstrations/givens_rotations/lego-circuit.svg
  demonstrations/givens_rotations/orbitals+states.png
  demonstrations/tutorial_givens_rotations.py
  demos_basics.rst
Labels: merge-ready, qchem

#267 Add tutorial on molecular geometry optimization
  demonstrations/mol_geo_opt/fig_circuit.png
  demonstrations/mol_geo_opt/fig_movie.gif
  demonstrations/mol_geo_opt/fig_pes.png
  demonstrations/mol_geo_opt/fig_thumbnail.png
  demonstrations/tutorial_mol_geo_opt.py
  demos_research.rst
Labels: merge-ready, qchem

#266 Add demonstration for kernels module
  _static/thumbs/spsa_mntn.png
  demonstrations/kernels_module/QEK_thumbnail.png
  demonstrations/kernels_module/embedding_nonlinear_classification.png
  demonstrations/kernels_module/linear_classification.png
  demonstrations/tutorial_kernels_module.py
  demos_research.rst
Labels: merge-ready

#282 Refactor the tutorial "Quantum Chemistry with PennyLane"
  demonstrations/quantum_chemistry/water_structure.png
  demonstrations/tutorial_quantum_chemistry.py
Labels: qchem

#293 Refactor the tutorial "A brief overview of VQE"
  demonstrations/tutorial_vqe.py
  demonstrations/variational_quantum_eigensolver/sketch_circuit.png
Labels: qchem

#271 Quantum Analytic Descent Demo
  demonstrations/quantum_analytic_descent/flowchart.png
  demonstrations/quantum_analytic_descent/xkcd.png
  demonstrations/tutorial_quantum_analytic_descent.py
  demos_research.rst
  xanadu_theme/static/xanadu.css_t
Labels: merge-ready, review-ready

#304 Add missed suggestion to the tutorial "Building molecular Hamiltonians"
  demonstrations/tutorial_quantum_chemistry.py
Labels: demos, qchem

#261 Tutorial on studying chemical reactions using VQE
  demonstrations/tutorial_chemical_reactions.py
  demonstrations/vqe_bond_dissociation/H2_Be.png
  demonstrations/vqe_bond_dissociation/H2_Be_VQE.png
  demonstrations/vqe_bond_dissociation/beh2_movie.gif
  demonstrations/vqe_bond_dissociation/h2.png
  demonstrations/vqe_bond_dissociation/h2_dissociation.png
  demonstrations/vqe_bond_dissociation/h2_pes.png
  demonstrations/vqe_bond_dissociation/h2_pes_pictorial.png
  demonstrations/vqe_bond_dissociation/h3_comparison.png
  demonstrations/vqe_bond_dissociation/h3_mol_movie.gif
  demonstrations/vqe_bond_dissociation/pes.png
  demonstrations/vqe_bond_dissociation/reaction.png
  demonstrations/vqe_bond_dissociation/test.png
  demos_basics.rst
  requirements.txt
Labels: qchem

#299 Refactor tutorial "VQE in different spin sectors"
  demonstrations/tutorial_vqe_spin_sectors.py
  demonstrations/tutorial_vqe_uccsd_obs.py
  demonstrations/vqe_spin_sectors/energy_spectra_h2_sto3g.png
  demonstrations/vqe_spin_sectors/fig_excitations.png
  demonstrations/vqe_spin_sectors/thumbnail_spectra_h2.png
  demos_basics.rst
Labels: demos, qchem
