Repository PennyLaneAI/qml, pull requests merged in 2022-08, with the labels that each got.

#532 Removed search page from theme
  .github/workflows/build-pr.yml
  .github/workflows/github_job_scheduler.py
  _templates/search.html
  conf.py
  xanadu_theme/search.html
  xanadu_theme/searchbox.html
Labels: bug

#537 Update build pipeline invalidate cache
  .github/workflows/build-pr.yml
Labels: enhancement

#543 Fix QML pipeline bug to push changes to appropriate environment site
  .github/workflows/build-pr.yml
  .github/workflows/deploy-pr.yml
Labels: bug

#529 Differentiable error mitigation
  _static/authors/qottmann.jpg
  demonstrations/diffable-mitigation/Mitigate_real_vs_sim3.png
  demonstrations/diffable-mitigation/diffable_mitigation_thumb.png
  demonstrations/tutorial_diffable-mitigation.py
  demos_optimization.rst
Labels: review-ready

#489 Demo training with few data
  _static/authors/luis_mantilla.jpg
  _static/authors/maurice_weber.jpeg
  _static/authors/qottmann.jpeg
  demonstrations/learning_few_data/cnn_pic.png
  demonstrations/learning_few_data/few_data_thumbnail.png
  demonstrations/learning_few_data/overfitting.png
  demonstrations/learning_few_data/qcnn-architecture.png
  demonstrations/learning_few_data/true_vs_sample.png
  demonstrations/tutorial_learning_few_data.py
  demos_qml.rst
  requirements.txt
Labels: review-ready
