Repository PennyLaneAI/qml, pull requests merged in 2022-11, with the labels that each got.

#633 [Do Not Merge] Merge dev into master Post release!
  .github/workflows/build-dev.yml
  .github/workflows/build-master.yml
  .github/workflows/demo_diff_check.yml
  _static/authors/utkarsh_azad.txt
  _templates/filters.html
  demonstrations/braket-parallel-gradients.py
  demonstrations/ensemble_multi_qpu.py
  demonstrations/pytorch_noise.py
  demonstrations/qsim_beyond_classical.py
  demonstrations/tutorial_qubit_tapering.py
  demonstrations/tutorial_variational_classifier.py
  demonstrations/tutorial_vqe.py
  demonstrations/tutorial_vqe_spin_sectors.py
  demonstrations/vqe_parallel.py
  demos_getting-started.rst
  demos_qml.rst
  requirements.txt
Labels: do not merge

#639 [sc-29561]: Updated QML pipeline to retain downloadable python files included in demos
  .github/workflows/build-pr.yml
  .github/workflows/qml_pipeline_utils.py
Labels: bug, enhancement

#646 Pin setuptools to avoid breaking changes introduces in 65.6.0
  .github/workflows/build-pr.yml
Labels: bug

#558 Add quantum resource estimation demo
  _static/authors/reast.jpeg
  demonstrations/resource_estimation/qpe.png
  demonstrations/resource_estimation/qpe.svg
  demonstrations/resource_estimation/resource_estimation.jpeg
  demonstrations/tutorial_resource_estimation.py
  demos_quantum-chemistry.rst
Labels: qchem
