Repository PennyLaneAI/qml, pull requests merged in 2022-04, with the labels that each got.

#474 Remove QChem in the text
  demonstrations/tutorial_chemical_reactions.py
  demonstrations/tutorial_error_mitigation.py
  demonstrations/tutorial_givens_rotations.py
  demonstrations/tutorial_measurement_optimize.py
  demonstrations/tutorial_mol_geo_opt.py
  demonstrations/tutorial_quantum_chemistry.py
  demonstrations/tutorial_vqe.py
  demonstrations/tutorial_vqe_qng.py
  demonstrations/tutorial_vqe_spin_sectors.py
  demonstrations/vqe_parallel.py
Labels: qchem

#475 Update dependencies in quantum chemistry tutorial
  demonstrations/tutorial_quantum_chemistry.py
Labels: qchem

#478 Sc 17646 add author editor bios to bottom of QML demos
  README.md
  _static/author_bio.css
  _static/avatar.webp
  conf.py
  custom_directives.py
  xanadu_theme/layout.html
Labels: documentation, enhancement, good first issue, demos

#447 Development branch
  .circleci/config.yml
  conf.py
  demonstrations/quantum_volume.py
  demonstrations/spsa.py
  demonstrations/spsa/h2_vqe_noisy_shots_ibm.png
  demonstrations/tutorial_chemical_reactions.py
  demonstrations/tutorial_error_mitigation.py
  demonstrations/tutorial_givens_rotations.py
  demonstrations/tutorial_measurement_optimize.py
  demonstrations/tutorial_mol_geo_opt.py
  demonstrations/tutorial_quantum_chemistry.py
  demonstrations/tutorial_sc_qubits.py
  demonstrations/tutorial_vqe.py
  demonstrations/tutorial_vqe_qng.py
  demonstrations/tutorial_vqe_spin_sectors.py
  demonstrations/vqe_parallel.py
  requirements.txt
Labels: do not merge

#479 adds m1 Mac instructions
  README.md
  requirements-norun.txt
Labels: documentation

#483 Fix Soft 404 coverage issue for pennylane.ai/qml/search.html
  _templates/search.html
Labels: bug
