Repository PennyLaneAI/qml, pull requests merged in 2023-04, with the labels that each got.

#641 Update the adaptive demo
  demonstrations/adaptive_circuits/thumbnail_adaptive_circuits.png
  demonstrations/tutorial_adaptive_circuits.py
  demos_quantum-chemistry.rst
Labels: qchem, ignore-qml-cache

#745 Replace macros in demo "Here comes the SU(N)"
  demonstrations/tutorial_here_comes_the_sun.py
Labels: review-ready

#734 Sc 32461 notebook demo conveter
  notebook_converter/README.md
  notebook_converter/notebook_to_demo.py
  notebook_converter/requirements.txt
Labels: enhancement
