Repository PennyLaneAI/qml, pull requests merged in 2024-07, with the labels that each got.

#1104 [sc-63358] How to use Qiskit 1.0 with PennyLane
  _static/authors/isaac_de_vlugt.jpeg
  _static/authors/isaac_de_vlugt.txt
  _static/demonstration_assets/how_to_use_qiskit_1_with_pennylane/pl_real_world_example.png
  _static/demonstration_assets/how_to_use_qiskit_1_with_pennylane/qiskit_parameterized_circuit.png
  _static/demonstration_assets/regular_demo_thumbnails/thumbnail_HowToUseQiskit1WithPL.png
  demonstrations/how_to_use_qiskit1_with_pennylane.metadata.json
  demonstrations/how_to_use_qiskit1_with_pennylane.py
Labels: Completed/Ready

#1148 Update braket static demos; Update torch dependency
  demonstrations/ahs_aquila.py
  demonstrations/braket-parallel-gradients.py
  poetry.lock
  pyproject.toml
Labels: ci:build-all-qml-demos

#1150 Demo checks for v0.37
  demonstrations/getting_started_with_hybrid_jobs.metadata.json
  demonstrations/getting_started_with_hybrid_jobs.py
  demonstrations/oqc_pulse.metadata.json
  demonstrations/oqc_pulse.py
  demonstrations/qnspsa.metadata.json
  demonstrations/qnspsa.py
Labels: merge-ready

#1147 Update PL and plugin dependencies
  Makefile
  poetry.lock
  pyproject.toml
Labels: ci:build-all-qml-demos

#1117 [sc-68716] Your guide to PennyLane knowing Qiskit
  _static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_guide_to_pennylane_knowing_qiskit.png
  _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_guide_to_pennylane_knowing_qiskit.png
  _static/demo_thumbnails/regular_demo_thumbnails/thumbnail_guide_to_pennylane_knowing_qiskit.png
  _static/demonstration_assets/guide_to_pennylane_knowing_qiskit/pennylane_bell_circuit.png
  _static/demonstration_assets/guide_to_pennylane_knowing_qiskit/pennylane_bell_circuit_measure.png
  _static/demonstration_assets/guide_to_pennylane_knowing_qiskit/qiskit_bell_circuit.png
  demonstrations/how_to_use_qiskit1_with_pennylane.metadata.json
  demonstrations/tutorial_error_mitigation.py
  demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.metadata.json
  demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
  demonstrations/tutorial_spsa.py
  poetry.lock
  pyproject.toml
Labels: dependencies, ci:build-all-qml-demos

#1168 Add How-to category to select PennyLane Demos
  demonstrations/demonstrations_categories.metadata.json
  demonstrations/how_to_use_qiskit1_with_pennylane.metadata.json
  demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.metadata.json
  demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.metadata.json
  demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_catalyst_and_Optax.metadata.json
  demonstrations/tutorial_How_to_simulate_quantum_circuits_with_tensor_networks.metadata.json
  demonstrations/tutorial_error_prop.metadata.json
  demonstrations/tutorial_how_to_collect_mcm_stats.metadata.json
  demonstrations/tutorial_how_to_create_dynamic_mcm_circuits.metadata.json
  demonstrations/tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst.metadata.json
Labels: ci:build-all-qml-demos

#1174 update-sphinx-gallery-version
  poetry.lock
  pyproject.toml
Labels: ci:build-all-qml-demos
