Repository PennyLaneAI/qml, pull requests merged in 2024-12, with the labels that each got.

#1272 Updating `pennylane-qrack` to version 0.11.1 and `bluequbit`
  poetry.lock
  pyproject.toml
Labels: ci:build-all-qml-demos

#1263 QubitDevice removed from toplevel, along with their warnings
  conf.py
  demonstrations/tutorial_bluequbit.metadata.json
  demonstrations/tutorial_bluequbit.py
Labels: do not merge

#1211 Update qchem demos to be JAX or JAX/JIT compatible
  demonstrations/tutorial_adaptive_circuits.metadata.json
  demonstrations/tutorial_adaptive_circuits.py
  demonstrations/tutorial_chemical_reactions.metadata.json
  demonstrations/tutorial_chemical_reactions.py
  demonstrations/tutorial_classically_boosted_vqe.metadata.json
  demonstrations/tutorial_classically_boosted_vqe.py
  demonstrations/tutorial_eqnn_force_field.metadata.json
  demonstrations/tutorial_eqnn_force_field.py
  demonstrations/tutorial_givens_rotations.metadata.json
  demonstrations/tutorial_givens_rotations.py
  demonstrations/tutorial_initial_state_preparation.metadata.json
  demonstrations/tutorial_initial_state_preparation.py
  demonstrations/tutorial_measurement_optimize.metadata.json
  demonstrations/tutorial_measurement_optimize.py
  demonstrations/tutorial_qchem_external.metadata.json
  demonstrations/tutorial_qchem_external.py
  demonstrations/tutorial_qubit_tapering.metadata.json
  demonstrations/tutorial_qubit_tapering.py
  demonstrations/tutorial_vqe_spin_sectors.metadata.json
  demonstrations/tutorial_vqe_spin_sectors.py
Labels: merge-ready

#1226 Fix demos to use jax that require grads
  demonstrations/tutorial_differentiable_HF.metadata.json
  demonstrations/tutorial_differentiable_HF.py
  demonstrations/tutorial_fermionic_operators.metadata.json
  demonstrations/tutorial_fermionic_operators.py
  demonstrations/tutorial_mapping.metadata.json
  demonstrations/tutorial_mapping.py
  demonstrations/tutorial_mol_geo_opt.metadata.json
  demonstrations/tutorial_mol_geo_opt.py
  demonstrations/tutorial_resource_estimation.metadata.json
  demonstrations/tutorial_resource_estimation.py
Labels: merge-ready
